---
- name: Pull builder images
  containers.podman.podman_image:
    name: "{{ item }}"
    username: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    force: true
  loop:
    - "{{ ee_base_image }}"
    # - "{{ ee_builder_image }}"
  when: ee_version == 1 or ee_version == 3

- name: Login to PAH
  containers.podman.podman_login:
    username: "{{ pah_user }}"
    password: "{{ pah_pass }}"
    registry: "{{ pah_name }}"
  when: ee_version == 2

- name: Delete old EE
  containers.podman.podman_image:
    name: "{{ pah_name }}/{{ image_name }}"
    state: absent
    force: true

- name: Template out builder files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ dest_dir }}{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop:
    - ansible.cfg
    - bindep.txt
    - execution-environment.yml
    - requirements.txt
    - requirements.yml

- name: Build new EE on version 1 without signature verification
  ansible.builtin.command:
    cmd: 'ansible-builder build -t {{ pah_name }}/{{ image_name }} --prune-images --galaxy-keyring={{ galaxy_keyring }}'
    chdir: "{{ dest_dir }}"
  changed_when: true
  when: ee_version == 1

- name: Build new EE with container signature verification on version 2 or 3
  ansible.builtin.command:
    cmd: 'ansible-builder build -t {{ pah_name }}/{{ image_name }} --prune-images --galaxy-keyring={{ galaxy_keyring }} --container-policy=system'
    chdir: "{{ dest_dir }}"
  changed_when: true
  when: ee_version == 2 or ee_version == 3

- name: Create new tag on EE based on date time of creation
  containers.podman.podman_tag:
    image: "{{ pah_name }}/{{ image_name }}"
    target_names:
      - "{{ pah_name }}/{{ image_name }}:{{ ansible_date_time.iso8601_basic_short }}"

- name: Push new EE
  containers.podman.podman_image:
    name: "{{ pah_name }}/{{ image_name }}"
    tag: "{{ item }}"
    push: true
    username: "{{ pah_user }}"
    password: "{{ pah_pass }}"
  loop:
    - "{{ ansible_date_time.iso8601_basic_short }}"
    - latest

- name: Remove extra tag
  containers.podman.podman_image:
    name: "{{ pah_name }}/{{ image_name }}"
    tag: "{{ ansible_date_time.iso8601_basic_short }}"
    state: absent

- name: Update Execution Environment Version in Controller with new version
  ansible.controller.execution_environment:
    name: "EE Creation EE"
    image: "{{ pah_name }}/{{ image_name }}:{{ ansible_date_time.iso8601_basic_short }}"
  delegate_to: localhost
