---
ee_version: 3
dest_dir: /home/ansible/ansible/builder/securityee/
pah_name: aap.shadowman.dev
image_name: securityee
galaxy_requirements_file: requirements.yml
ee_base_image: aap.shadowman.dev/ansible-automation-platform/ee-minimal-rhel9:2.16
ee_base_sig_name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.16
galaxy_keyring: /certs/fullkeyring.kbx
ee_package_manager_path: /usr/bin/microdnf
ee_python_interpreter:
  python_path: "/usr/bin/python3.11"
ee_build_files:
  - src: /home/ansible/ansible/builder/securityee/ansible.cfg
    dest: configs
ee_collections:
  - name: ansible.windows
  - name: community.crypto
  - name: community.general
    version: 11.4.1
  - name: ibm.qradar
  - name: paloaltonetworks.panos
  - name: shadowman.reports
ee_prepend_galaxy:
  - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
ee_append_final:
  - RUN rm -f /etc/ansible/ansible.cfg
  - RUN microdnf clean all
