---

- name: Ensure old EE is removed
  ansible.builtin.command:
    cmd: "podman rmi aaphub.shadowman.dev/full/ansibleee"
  changed_when: true

- name: Build new EE
  ansible.builtin.command:
    cmd: "ansible-builder build -t aaphub.shadowman.dev/full/ansibleee"
    chdir: /home/adworjan/ansible/execution/
  changed_when: true

- name: Remove <none> images after build
  ansible.builtin.shell:
    cmd: podman rmi $(podman images -f 'dangling=true' -q)
  changed_when: true

- name: push new EE to PAH
  ansible.builtin.command:
    cmd: "podman push --creds={{pah_user}}:{{pah_pass}} aaphub.shadowman.dev/full/ansibleee"
  changed_when: true