---
ee_version: 3
dest_dir: /home/ansible/ansible/builder/nmapee/
pah_name: aap.shadowman.dev
image_name: nmapee
galaxy_requirements_file: requirements.yml
bindep_file: bindep.txt
ee_base_image: aap.shadowman.dev/ansible-automation-platform/ee-minimal-rhel9:2.18
ee_base_sig_name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9:2.18
galaxy_keyring: /certs/fullkeyring.kbx
ee_package_manager_path: /usr/bin/microdnf
ee_python_interpreter:
  python_path: "/usr/bin/python3.11"
ee_build_files:
  - src: /home/ansible/ansible/builder/nmapee/ansible.cfg
    dest: configs
ee_bindep:
  - nmap [platform:rpm]
  - sudo [platform:rpm]
ee_collections:
  - name: community.general
ee_prepend_galaxy:
  - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
ee_append_final:
  - RUN rm -f /etc/ansible/ansible.cfg
  - RUN microdnf clean all
  - CAP_ADD CAP_NET_RAW
  - CAP_ADD NET_RAW
